name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签出存储库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: 设置 JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 设置 Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 使 Gradle 包装器可执行
        run: chmod +x ./gradlew

      - name: 数据生成
        run: ./gradlew runData

      - name: 使用 Gradle 构建
        run: ./gradlew build

      - name: 上传生成项目
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/libs/*.jar